### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Aslonski** [gztchan/awesome-design#35]
Hi, 
I cloned your repo and added a great tutorial resource in the README.md file. But when I tried to push my branch to master I got permission denied. How can I submit the pull request? 
Thanks!

**Comment by llvasconcellos** [comment]
Submit the branch as a PR.

Leonardo Lima de Vasconcellos
Analista de Sistemas
leonardo@devhouse.com.br
------------------------------
[image: dmg]

www.devhouse.com.br
Sistemas ▪ E-Commerce ▪ WebSites ▪ Hospedagem


2016-09-15 11:53 GMT-03:00 Andrey Slonski <notifications@github.com>:

**Comment by gztchan** [comment]
@Aslonski You can create pull request, and then I will review your resources. Let's try 😄

**Comment by Aslonski** [comment]
@gztchan When I click on create pull request I have no option to actually create one. So I'm a little confused

**Comment by corygibbons** [comment]
@Aslonski You need to create a pull request from within your fork.

**Comment by cprogrammer1994** [comment]
Maybe you forgot to fork and just cloned the repo.

**Comment by gztchan** [comment]
@Aslonski resolved ?

**Comment by gztchan** [comment]
close
