### ISSUE TITLE
More useful description for prototype apps

### ISSUE THREAD

**Issue by dvkndn** [gztchan/awesome-design#47]
Hi guys, I think some descriptions are not so useful, for example:

> Marvel - Simple design, prototyping and collaboration.
> InVision - The world's leading prototyping, collaboration & workflow platform.
> Origami - Design Prototyping.
> Framer.js - Design tool for creating interactive designs, interfaces and animations.
> Atomic - The prototyping tool designed for teams.
> Pixate - Make your ideas a reality.

These descriptions tell the same thing: "I am a prototype app". However, I think I can improve this because there are many differences in their targets and usages. For example, to build a prototype, Framer.js focus on the use of code, while Pixate offers a drag and drop interface. Or about the target, InVision and Marvel focus on the navigation between multiple screens, while Pixate, Framer.js focus on complex interaction inside a screen.

Therefore, I'd like to create a pull request to improve these descriptions, based on their usage and target instead of using their slogan.

Do you guys think this is a useful thing to do? I'm asking this because I see there are many PRs already so I want to avoid working on something not useful.

Please tell me what you guys think about this?

**Comment by gztchan** [comment]
Of course yes. It seems that you have some experience on them, Please feel free to write something!! Help more people design great things. 👍

**Comment by gztchan** [comment]
@dvkndn I will try my best to review all issues and PRs, which are important to this repo. So, Don't worry about that.

**Comment by dvkndn** [comment]
Thank you. I'm adding right now. I used to be a UI designer so I really want to contribute on this one

**Comment by stormyyz** [comment]
It seems right to me!
