### ISSUE TITLE
x-pages.xyz

### ISSUE THREAD

**Issue by tchret** [gztchan/awesome-design#6]
[pricingpages.xyz](pricingpages.xyz)
[productpages.xyz](productpages.xyz)
[checkoutpages.xyz](checkoutpages.xyz)
[storepages.xyz](storepages.xyz)

✌️

**Comment by gztchan** [comment]
[a1b866f50eabe740fa73c9b2011cb9820076afdf](https://github.com/gztchan/awesome-design/commit/a1b866f50eabe740fa73c9b2011cb9820076afdf)
