### ISSUE TITLE
Pixate no more

### ISSUE THREAD

**Issue by shnbwmn** [gztchan/awesome-design#65]
[Pixate](http://www.pixate.com/), listed under **[Prototype](https://github.com/gztchan/awesome-design#prototype-memo)** 📝, has been discontinued.

Notice on the homepage:

> **Saying farewell to Pixate.**
> 
> When we launched Pixate over 2 years ago, our mission was to change the way mobile apps were prototyped. We joined Google just over a year ago to continue our mission, and to pursue a broader vision of changing the way products were designed and built.
> 
> While a lot of the ideas we’ve been developing could work inside the Pixate framework, we believe we can have a larger impact if we move beyond its scope. To allow us to focus on our broader vision, we will be to saying goodbye to Pixate.
> 
> You can read more about the announcement, and what this means to you, on our [blog](http://blog.pixate.com/).
> 
> — The Pixate team 👋

Also - you indicate that it's MacOS only 💻, however last year it was certainly available on Windows (that's how I started using it). This is also evidenced in the above blog post link.

**Comment by gztchan** [comment]
[bb972b0781339f5e0549726db82134b6ce8cc3f9](https://github.com/gztchan/awesome-design/commit/bb972b0781339f5e0549726db82134b6ce8cc3f9)

Thank you for this infomation. 👍  And also appreciate Pixate team for the product. 💯
