### ISSUE TITLE
How to add this resource in list ?

### ISSUE THREAD

**Issue by SangramChavan** [gztchan/awesome-design#71]
https://cdn-images-1.medium.com/max/800/1*Qf6_zsIAM1WYhL93yqoP0g.png

**Comment by SangramChavan** [comment]
`https://cdn-images-1.medium.com/max/800/1*Qf6_zsIAM1WYhL93yqoP0g.png`

**Comment by gztchan** [comment]
is it a feature of Google images?

**Comment by SangramChavan** [comment]
Yes, it is a feature may be helpful for many.
