### ISSUE TITLE
Remove dead links

### ISSUE THREAD

**Issue by ReadmeCritic** [gztchan/awesome-design#81]
1. `line 94`  http://greatappstimeline.xyz/ `Connection timed out - connect(2) for "greatappstimeline.xyz" port 80` 
  2. `line 245`  http://colorschemr.com/#/app `getaddrinfo: Name or service not known`

**Comment by meeladdawood** [comment]
I removed all the dead links that were in the README.

**Comment by gztchan** [comment]
Thanks🌟
